name: Hypothesis
run-name: ${{ github.actor }} is testing GHA Shell Cascading
on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Setting variables that should NOT cascade through steps
        run: set -euo pipefail
        shell: bash

      - name: Plain Bash Entry (no errexit)
        if: always()
        run: |
          cat some-file-that-does-not-exist-throws-errors.txt
          echo 'Exiting with code 55 if errexit is not enabled'
          exit 55
        shell: /usr/bin/bash {0}

      - name: Plain Bash Entry (with errexit)
        if: always()
        run: |
          set -euo pipefail
          cat some-file-that-does-not-exist-throws-errors.txt
          echo 'Exiting with code 55 if errexit is not enabled'
          exit 55
        shell: /usr/bin/bash {0}

      - name: GitHub Actions Bash Entry
        if: always()
        run: |
          cat some-file-that-does-not-exist-throws-errors.txt
          echo 'Exiting with code 55 if errexit is not enabled'
          exit 55
        shell: bash

      - name: GitHub Actions Bash Entry (disabled errexit)
        if: always()
        run: |
          set +e
          cat some-file-that-does-not-exist-throws-errors.txt
          echo 'Exiting with code 55 if errexit is not enabled'
          exit 55
        shell: bash
